/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const CoursewareProduct = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'inventory' : IDL.Nat,
  'description' : IDL.Text,
  'price' : IDL.Float64,
});
export const SOP = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'procedures' : IDL.Vec(IDL.Text),
  'qualityStandards' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'productionType' : IDL.Text,
  'roles' : IDL.Vec(IDL.Text),
  'documentationRequirements' : IDL.Vec(IDL.Text),
});
export const ContactFormSubmission = IDL.Record({
  'id' : IDL.Nat,
  'interests' : IDL.Text,
  'name' : IDL.Text,
  'timestamp' : IDL.Int,
  'location' : IDL.Text,
  'contactDetails' : IDL.Text,
});
export const FarmerSuccessStory = IDL.Record({
  'id' : IDL.Nat,
  'technique' : IDL.Text,
  'outcome' : IDL.Text,
  'location' : IDL.Text,
  'farmerName' : IDL.Text,
});
export const FarmingTechnique = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'benefits' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'farmingArea' : IDL.Text,
  'submittedAt' : Time,
  'testimonialText' : IDL.Text,
  'approved' : IDL.Bool,
  'location' : IDL.Text,
  'farmerName' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'endDate' : Time,
  'description' : IDL.Text,
  'instructorId' : IDL.Principal,
  'productionType' : IDL.Text,
  'startDate' : Time,
});
export const Enrollment = IDL.Record({
  'id' : IDL.Nat,
  'traineeId' : IDL.Principal,
  'progress' : IDL.Nat,
  'courseId' : IDL.Nat,
});
export const GdpImpactStat = IDL.Record({
  'trainedFarmers' : IDL.Nat,
  'gdpProgress' : IDL.Float64,
  'yieldImprovements' : IDL.Float64,
  'revenueGenerated' : IDL.Float64,
});
export const ProductionMetric = IDL.Record({
  'id' : IDL.Nat,
  'value' : IDL.Float64,
  'productionType' : IDL.Text,
  'timestamp' : Time,
  'metricName' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'endDate' : IDL.Opt(Time),
  'description' : IDL.Text,
  'productionType' : IDL.Text,
  'outcomes' : IDL.Text,
  'startDate' : Time,
});
export const NewsItem = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
});
export const TeamMember = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'expertise' : IDL.Text,
});
export const PublicContent = IDL.Record({
  'mission' : IDL.Text,
  'news' : IDL.Vec(NewsItem),
  'team' : IDL.Vec(TeamMember),
  'goals' : IDL.Text,
  'vision' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCoursewareProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
      [],
      [],
    ),
  'addFarmingTechnique' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addProductionMetric' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'addSectorTemplate' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'addSuccessStory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'approveTestimonial' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCourse' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Principal, Time, Time, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time, IDL.Opt(Time), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createSop' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteSop' : IDL.Func([IDL.Nat], [], []),
  'deleteTestimonial' : IDL.Func([IDL.Nat], [], []),
  'enrollInCourse' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'getAchievements' : IDL.Func(
      [],
      [
        IDL.Record({
          'ongoingCourses' : IDL.Nat,
          'completedCourses' : IDL.Nat,
          'achievements' : IDL.Vec(IDL.Text),
        }),
      ],
      ['query'],
    ),
  'getAllCourseware' : IDL.Func([], [IDL.Vec(CoursewareProduct)], ['query']),
  'getAllSops' : IDL.Func([], [IDL.Vec(SOP)], ['query']),
  'getAllSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getAllSuccessStories' : IDL.Func(
      [],
      [IDL.Vec(FarmerSuccessStory)],
      ['query'],
    ),
  'getAllTechniques' : IDL.Func([], [IDL.Vec(FarmingTechnique)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getApprovedTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourse' : IDL.Func([IDL.Nat], [Course], ['query']),
  'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getCoursesByProductionType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Course)],
      ['query'],
    ),
  'getEnrollmentsForTrainee' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Enrollment)],
      ['query'],
    ),
  'getGdpStats' : IDL.Func([], [GdpImpactStat], ['query']),
  'getMetricsByType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProductionMetric)],
      ['query'],
    ),
  'getProjectsByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Project)], ['query']),
  'getProjectsByType' : IDL.Func([IDL.Text], [IDL.Vec(Project)], ['query']),
  'getPublicContent' : IDL.Func([], [PublicContent], ['query']),
  'getSop' : IDL.Func([IDL.Nat], [SOP], ['query']),
  'getSopsByProductionType' : IDL.Func([IDL.Text], [IDL.Vec(SOP)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProgress' : IDL.Func(
      [],
      [
        IDL.Record({
          'profile' : IDL.Opt(UserProfile),
          'enrollments' : IDL.Vec(Enrollment),
        }),
      ],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'purchaseCourseware' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitTestimonial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateEnrollmentProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateGdpStats' : IDL.Func(
      [IDL.Float64, IDL.Nat, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'updatePublicContent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(TeamMember), IDL.Vec(NewsItem)],
      [],
      [],
    ),
  'updateSop' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'updateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [UserProfile],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const CoursewareProduct = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'inventory' : IDL.Nat,
    'description' : IDL.Text,
    'price' : IDL.Float64,
  });
  const SOP = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'procedures' : IDL.Vec(IDL.Text),
    'qualityStandards' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'productionType' : IDL.Text,
    'roles' : IDL.Vec(IDL.Text),
    'documentationRequirements' : IDL.Vec(IDL.Text),
  });
  const ContactFormSubmission = IDL.Record({
    'id' : IDL.Nat,
    'interests' : IDL.Text,
    'name' : IDL.Text,
    'timestamp' : IDL.Int,
    'location' : IDL.Text,
    'contactDetails' : IDL.Text,
  });
  const FarmerSuccessStory = IDL.Record({
    'id' : IDL.Nat,
    'technique' : IDL.Text,
    'outcome' : IDL.Text,
    'location' : IDL.Text,
    'farmerName' : IDL.Text,
  });
  const FarmingTechnique = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'benefits' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'farmingArea' : IDL.Text,
    'submittedAt' : Time,
    'testimonialText' : IDL.Text,
    'approved' : IDL.Bool,
    'location' : IDL.Text,
    'farmerName' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'endDate' : Time,
    'description' : IDL.Text,
    'instructorId' : IDL.Principal,
    'productionType' : IDL.Text,
    'startDate' : Time,
  });
  const Enrollment = IDL.Record({
    'id' : IDL.Nat,
    'traineeId' : IDL.Principal,
    'progress' : IDL.Nat,
    'courseId' : IDL.Nat,
  });
  const GdpImpactStat = IDL.Record({
    'trainedFarmers' : IDL.Nat,
    'gdpProgress' : IDL.Float64,
    'yieldImprovements' : IDL.Float64,
    'revenueGenerated' : IDL.Float64,
  });
  const ProductionMetric = IDL.Record({
    'id' : IDL.Nat,
    'value' : IDL.Float64,
    'productionType' : IDL.Text,
    'timestamp' : Time,
    'metricName' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'endDate' : IDL.Opt(Time),
    'description' : IDL.Text,
    'productionType' : IDL.Text,
    'outcomes' : IDL.Text,
    'startDate' : Time,
  });
  const NewsItem = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
  });
  const TeamMember = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'expertise' : IDL.Text,
  });
  const PublicContent = IDL.Record({
    'mission' : IDL.Text,
    'news' : IDL.Vec(NewsItem),
    'team' : IDL.Vec(TeamMember),
    'goals' : IDL.Text,
    'vision' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCoursewareProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
        [],
        [],
      ),
    'addFarmingTechnique' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addProductionMetric' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'addSectorTemplate' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'addSuccessStory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'approveTestimonial' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCourse' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Principal, Time, Time, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time, IDL.Opt(Time), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createSop' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteSop' : IDL.Func([IDL.Nat], [], []),
    'deleteTestimonial' : IDL.Func([IDL.Nat], [], []),
    'enrollInCourse' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'getAchievements' : IDL.Func(
        [],
        [
          IDL.Record({
            'ongoingCourses' : IDL.Nat,
            'completedCourses' : IDL.Nat,
            'achievements' : IDL.Vec(IDL.Text),
          }),
        ],
        ['query'],
      ),
    'getAllCourseware' : IDL.Func([], [IDL.Vec(CoursewareProduct)], ['query']),
    'getAllSops' : IDL.Func([], [IDL.Vec(SOP)], ['query']),
    'getAllSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getAllSuccessStories' : IDL.Func(
        [],
        [IDL.Vec(FarmerSuccessStory)],
        ['query'],
      ),
    'getAllTechniques' : IDL.Func([], [IDL.Vec(FarmingTechnique)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getApprovedTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourse' : IDL.Func([IDL.Nat], [Course], ['query']),
    'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getCoursesByProductionType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Course)],
        ['query'],
      ),
    'getEnrollmentsForTrainee' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Enrollment)],
        ['query'],
      ),
    'getGdpStats' : IDL.Func([], [GdpImpactStat], ['query']),
    'getMetricsByType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProductionMetric)],
        ['query'],
      ),
    'getProjectsByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Project)], ['query']),
    'getProjectsByType' : IDL.Func([IDL.Text], [IDL.Vec(Project)], ['query']),
    'getPublicContent' : IDL.Func([], [PublicContent], ['query']),
    'getSop' : IDL.Func([IDL.Nat], [SOP], ['query']),
    'getSopsByProductionType' : IDL.Func([IDL.Text], [IDL.Vec(SOP)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProgress' : IDL.Func(
        [],
        [
          IDL.Record({
            'profile' : IDL.Opt(UserProfile),
            'enrollments' : IDL.Vec(Enrollment),
          }),
        ],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'purchaseCourseware' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateEnrollmentProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateGdpStats' : IDL.Func(
        [IDL.Float64, IDL.Nat, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'updatePublicContent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(TeamMember), IDL.Vec(NewsItem)],
        [],
        [],
      ),
    'updateSop' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'updateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [UserProfile],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };