/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ContactFormSubmission {
  'id' : bigint,
  'interests' : string,
  'name' : string,
  'timestamp' : bigint,
  'location' : string,
  'contactDetails' : string,
}
export interface Course {
  'id' : bigint,
  'title' : string,
  'endDate' : Time,
  'description' : string,
  'instructorId' : Principal,
  'productionType' : string,
  'startDate' : Time,
}
export interface CoursewareProduct {
  'id' : bigint,
  'title' : string,
  'inventory' : bigint,
  'description' : string,
  'price' : number,
}
export interface Enrollment {
  'id' : bigint,
  'traineeId' : Principal,
  'progress' : bigint,
  'courseId' : bigint,
}
export interface FarmerSuccessStory {
  'id' : bigint,
  'technique' : string,
  'outcome' : string,
  'location' : string,
  'farmerName' : string,
}
export interface FarmingTechnique {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'benefits' : string,
}
export interface GdpImpactStat {
  'trainedFarmers' : bigint,
  'gdpProgress' : number,
  'yieldImprovements' : number,
  'revenueGenerated' : number,
}
export interface NewsItem {
  'title' : string,
  'content' : string,
  'date' : Time,
}
export interface ProductionMetric {
  'id' : bigint,
  'value' : number,
  'productionType' : string,
  'timestamp' : Time,
  'metricName' : string,
}
export interface Project {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'endDate' : [] | [Time],
  'description' : string,
  'productionType' : string,
  'outcomes' : string,
  'startDate' : Time,
}
export interface PublicContent {
  'mission' : string,
  'news' : Array<NewsItem>,
  'team' : Array<TeamMember>,
  'goals' : string,
  'vision' : string,
}
export interface SOP {
  'id' : bigint,
  'title' : string,
  'procedures' : Array<string>,
  'qualityStandards' : Array<string>,
  'description' : string,
  'productionType' : string,
  'roles' : Array<string>,
  'documentationRequirements' : Array<string>,
}
export interface TeamMember {
  'name' : string,
  'role' : string,
  'expertise' : string,
}
export interface Testimonial {
  'id' : bigint,
  'farmingArea' : string,
  'submittedAt' : Time,
  'testimonialText' : string,
  'approved' : boolean,
  'location' : string,
  'farmerName' : string,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'id' : Principal,
  'bio' : string,
  'name' : string,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCoursewareProduct' : ActorMethod<
    [string, string, number, bigint],
    undefined
  >,
  'addFarmingTechnique' : ActorMethod<[string, string, string], undefined>,
  'addProductionMetric' : ActorMethod<[string, string, number], bigint>,
  'addSectorTemplate' : ActorMethod<[string], bigint>,
  'addSuccessStory' : ActorMethod<[string, string, string, string], undefined>,
  'approveTestimonial' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCourse' : ActorMethod<
    [string, string, Principal, Time, Time, string],
    bigint
  >,
  'createProject' : ActorMethod<
    [string, string, string, string, Time, [] | [Time], string],
    bigint
  >,
  'createSop' : ActorMethod<
    [
      string,
      string,
      string,
      Array<string>,
      Array<string>,
      Array<string>,
      Array<string>,
    ],
    bigint
  >,
  'deleteSop' : ActorMethod<[bigint], undefined>,
  'deleteTestimonial' : ActorMethod<[bigint], undefined>,
  'enrollInCourse' : ActorMethod<[bigint], bigint>,
  'getAchievements' : ActorMethod<
    [],
    {
      'ongoingCourses' : bigint,
      'completedCourses' : bigint,
      'achievements' : Array<string>,
    }
  >,
  'getAllCourseware' : ActorMethod<[], Array<CoursewareProduct>>,
  'getAllSops' : ActorMethod<[], Array<SOP>>,
  'getAllSubmissions' : ActorMethod<[], Array<ContactFormSubmission>>,
  'getAllSuccessStories' : ActorMethod<[], Array<FarmerSuccessStory>>,
  'getAllTechniques' : ActorMethod<[], Array<FarmingTechnique>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getApprovedTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourse' : ActorMethod<[bigint], Course>,
  'getCourses' : ActorMethod<[], Array<Course>>,
  'getCoursesByProductionType' : ActorMethod<[string], Array<Course>>,
  'getEnrollmentsForTrainee' : ActorMethod<[Principal], Array<Enrollment>>,
  'getGdpStats' : ActorMethod<[], GdpImpactStat>,
  'getMetricsByType' : ActorMethod<[string], Array<ProductionMetric>>,
  'getProjectsByStatus' : ActorMethod<[string], Array<Project>>,
  'getProjectsByType' : ActorMethod<[string], Array<Project>>,
  'getPublicContent' : ActorMethod<[], PublicContent>,
  'getSop' : ActorMethod<[bigint], SOP>,
  'getSopsByProductionType' : ActorMethod<[string], Array<SOP>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProgress' : ActorMethod<
    [],
    { 'profile' : [] | [UserProfile], 'enrollments' : Array<Enrollment> }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'purchaseCourseware' : ActorMethod<[bigint, bigint], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'submitTestimonial' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'updateEnrollmentProgress' : ActorMethod<[bigint, bigint], undefined>,
  'updateGdpStats' : ActorMethod<[number, bigint, number, number], undefined>,
  'updatePublicContent' : ActorMethod<
    [string, string, string, Array<TeamMember>, Array<NewsItem>],
    undefined
  >,
  'updateSop' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      Array<string>,
      Array<string>,
      Array<string>,
      Array<string>,
    ],
    undefined
  >,
  'updateUserProfile' : ActorMethod<[string, string, string], UserProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];