/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface GdpImpactStat {
    trainedFarmers: bigint;
    gdpProgress: number;
    yieldImprovements: number;
    revenueGenerated: number;
}
export interface FarmingTechnique {
    id: bigint;
    title: string;
    description: string;
    benefits: string;
}
export type Time = bigint;
export interface CoursewareProduct {
    id: bigint;
    title: string;
    inventory: bigint;
    description: string;
    price: number;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Enrollment {
    id: bigint;
    traineeId: Principal;
    progress: bigint;
    courseId: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface NewsItem {
    title: string;
    content: string;
    date: Time;
}
export interface PublicContent {
    mission: string;
    news: Array<NewsItem>;
    team: Array<TeamMember>;
    goals: string;
    vision: string;
}
export interface ProductionMetric {
    id: bigint;
    value: number;
    productionType: string;
    timestamp: Time;
    metricName: string;
}
export interface Course {
    id: bigint;
    title: string;
    endDate: Time;
    description: string;
    instructorId: Principal;
    productionType: string;
    startDate: Time;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface ContactFormSubmission {
    id: bigint;
    interests: string;
    name: string;
    timestamp: bigint;
    location: string;
    contactDetails: string;
}
export interface TeamMember {
    name: string;
    role: string;
    expertise: string;
}
export interface SOP {
    id: bigint;
    title: string;
    procedures: Array<string>;
    qualityStandards: Array<string>;
    description: string;
    productionType: string;
    roles: Array<string>;
    documentationRequirements: Array<string>;
}
export interface Project {
    id: bigint;
    status: string;
    title: string;
    endDate?: Time;
    description: string;
    productionType: string;
    outcomes: string;
    startDate: Time;
}
export interface FarmerSuccessStory {
    id: bigint;
    technique: string;
    outcome: string;
    location: string;
    farmerName: string;
}
export interface UserProfile {
    id: Principal;
    bio: string;
    name: string;
    role: UserRole;
    email: string;
}
export interface Testimonial {
    id: bigint;
    farmingArea: string;
    submittedAt: Time;
    testimonialText: string;
    approved: boolean;
    location: string;
    farmerName: string;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCoursewareProduct(title: string, description: string, price: number, inventory: bigint): Promise<void>;
    addFarmingTechnique(title: string, description: string, benefits: string): Promise<void>;
    addProductionMetric(productionType: string, metricName: string, value: number): Promise<bigint>;
    addSectorTemplate(_sector: string): Promise<bigint>;
    addSuccessStory(farmerName: string, location: string, technique: string, outcome: string): Promise<void>;
    approveTestimonial(testimonialId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCourse(title: string, description: string, instructorId: Principal, startDate: Time, endDate: Time, productionType: string): Promise<bigint>;
    createProject(title: string, description: string, productionType: string, status: string, startDate: Time, endDate: Time | null, outcomes: string): Promise<bigint>;
    createSop(title: string, description: string, productionType: string, procedures: Array<string>, roles: Array<string>, qualityStandards: Array<string>, documentationRequirements: Array<string>): Promise<bigint>;
    deleteSop(sopId: bigint): Promise<void>;
    deleteTestimonial(testimonialId: bigint): Promise<void>;
    enrollInCourse(courseId: bigint): Promise<bigint>;
    getAchievements(): Promise<{
        ongoingCourses: bigint;
        completedCourses: bigint;
        achievements: Array<string>;
    }>;
    getAllCourseware(): Promise<Array<CoursewareProduct>>;
    getAllSops(): Promise<Array<SOP>>;
    getAllSubmissions(): Promise<Array<ContactFormSubmission>>;
    getAllSuccessStories(): Promise<Array<FarmerSuccessStory>>;
    getAllTechniques(): Promise<Array<FarmingTechnique>>;
    getAllTestimonials(): Promise<Array<Testimonial>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getApprovedTestimonials(): Promise<Array<Testimonial>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCourse(courseId: bigint): Promise<Course>;
    getCourses(): Promise<Array<Course>>;
    getCoursesByProductionType(productionType: string): Promise<Array<Course>>;
    getEnrollmentsForTrainee(traineeId: Principal): Promise<Array<Enrollment>>;
    getGdpStats(): Promise<GdpImpactStat>;
    getMetricsByType(productionType: string): Promise<Array<ProductionMetric>>;
    getProjectsByStatus(status: string): Promise<Array<Project>>;
    getProjectsByType(productionType: string): Promise<Array<Project>>;
    getPublicContent(): Promise<PublicContent>;
    getSop(sopId: bigint): Promise<SOP>;
    getSopsByProductionType(productionType: string): Promise<Array<SOP>>;
    getUserProfile(userId: Principal): Promise<UserProfile | null>;
    getUserProgress(): Promise<{
        profile?: UserProfile;
        enrollments: Array<Enrollment>;
    }>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    purchaseCourseware(productId: bigint, quantity: bigint): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    submitContactForm(name: string, contactDetails: string, location: string, interests: string): Promise<void>;
    submitTestimonial(farmerName: string, location: string, farmingArea: string, testimonialText: string): Promise<void>;
    updateEnrollmentProgress(enrollmentId: bigint, progress: bigint): Promise<void>;
    updateGdpStats(yieldImprovements: number, trainedFarmers: bigint, revenueGenerated: number, gdpProgress: number): Promise<void>;
    updatePublicContent(mission: string, vision: string, goals: string, team: Array<TeamMember>, news: Array<NewsItem>): Promise<void>;
    updateSop(sopId: bigint, title: string, description: string, productionType: string, procedures: Array<string>, roles: Array<string>, qualityStandards: Array<string>, documentationRequirements: Array<string>): Promise<void>;
    updateUserProfile(name: string, email: string, bio: string): Promise<UserProfile>;
}
import type { ApprovalStatus as _ApprovalStatus, Enrollment as _Enrollment, Project as _Project, Time as _Time, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCoursewareProduct(arg0: string, arg1: string, arg2: number, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCoursewareProduct(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCoursewareProduct(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addFarmingTechnique(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFarmingTechnique(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFarmingTechnique(arg0, arg1, arg2);
            return result;
        }
    }
    async addProductionMetric(arg0: string, arg1: string, arg2: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProductionMetric(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProductionMetric(arg0, arg1, arg2);
            return result;
        }
    }
    async addSectorTemplate(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSectorTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSectorTemplate(arg0);
            return result;
        }
    }
    async addSuccessStory(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSuccessStory(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSuccessStory(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async approveTestimonial(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveTestimonial(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCourse(arg0: string, arg1: string, arg2: Principal, arg3: Time, arg4: Time, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCourse(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCourse(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createProject(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Time, arg5: Time | null, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async createSop(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: Array<string>, arg5: Array<string>, arg6: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSop(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSop(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async deleteSop(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSop(arg0);
            return result;
        }
    }
    async deleteTestimonial(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTestimonial(arg0);
            return result;
        }
    }
    async enrollInCourse(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.enrollInCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enrollInCourse(arg0);
            return result;
        }
    }
    async getAchievements(): Promise<{
        ongoingCourses: bigint;
        completedCourses: bigint;
        achievements: Array<string>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAchievements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAchievements();
            return result;
        }
    }
    async getAllCourseware(): Promise<Array<CoursewareProduct>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCourseware();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCourseware();
            return result;
        }
    }
    async getAllSops(): Promise<Array<SOP>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSops();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSops();
            return result;
        }
    }
    async getAllSubmissions(): Promise<Array<ContactFormSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubmissions();
            return result;
        }
    }
    async getAllSuccessStories(): Promise<Array<FarmerSuccessStory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSuccessStories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSuccessStories();
            return result;
        }
    }
    async getAllTechniques(): Promise<Array<FarmingTechnique>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTechniques();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTechniques();
            return result;
        }
    }
    async getAllTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTestimonials();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApprovedTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedTestimonials();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourse(arg0: bigint): Promise<Course> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return result;
        }
    }
    async getCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourses();
            return result;
        }
    }
    async getCoursesByProductionType(arg0: string): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoursesByProductionType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoursesByProductionType(arg0);
            return result;
        }
    }
    async getEnrollmentsForTrainee(arg0: Principal): Promise<Array<Enrollment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnrollmentsForTrainee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnrollmentsForTrainee(arg0);
            return result;
        }
    }
    async getGdpStats(): Promise<GdpImpactStat> {
        if (this.processError) {
            try {
                const result = await this.actor.getGdpStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGdpStats();
            return result;
        }
    }
    async getMetricsByType(arg0: string): Promise<Array<ProductionMetric>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMetricsByType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMetricsByType(arg0);
            return result;
        }
    }
    async getProjectsByStatus(arg0: string): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectsByStatus(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectsByStatus(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectsByType(arg0: string): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectsByType(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectsByType(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicContent(): Promise<PublicContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicContent();
            return result;
        }
    }
    async getSop(arg0: bigint): Promise<SOP> {
        if (this.processError) {
            try {
                const result = await this.actor.getSop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSop(arg0);
            return result;
        }
    }
    async getSopsByProductionType(arg0: string): Promise<Array<SOP>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSopsByProductionType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSopsByProductionType(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProgress(): Promise<{
        profile?: UserProfile;
        enrollments: Array<Enrollment>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProgress();
                return from_candid_record_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProgress();
            return from_candid_record_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async purchaseCourseware(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseCourseware(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseCourseware(arg0, arg1);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n29(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n29(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitTestimonial(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTestimonial(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTestimonial(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateEnrollmentProgress(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEnrollmentProgress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEnrollmentProgress(arg0, arg1);
            return result;
        }
    }
    async updateGdpStats(arg0: number, arg1: bigint, arg2: number, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGdpStats(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGdpStats(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updatePublicContent(arg0: string, arg1: string, arg2: string, arg3: Array<TeamMember>, arg4: Array<NewsItem>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePublicContent(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePublicContent(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateSop(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: Array<string>, arg5: Array<string>, arg6: Array<string>, arg7: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSop(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSop(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateUserProfile(arg0: string, arg1: string, arg2: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0, arg1, arg2);
                return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0, arg1, arg2);
            return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ApprovalStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    bio: string;
    name: string;
    role: _UserRole;
    email: string;
}): {
    id: Principal;
    bio: string;
    name: string;
    role: UserRole;
    email: string;
} {
    return {
        id: value.id,
        bio: value.bio,
        name: value.name,
        role: from_candid_UserRole_n14(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    title: string;
    endDate: [] | [_Time];
    description: string;
    productionType: string;
    outcomes: string;
    startDate: _Time;
}): {
    id: bigint;
    status: string;
    title: string;
    endDate?: Time;
    description: string;
    productionType: string;
    outcomes: string;
    startDate: Time;
} {
    return {
        id: value.id,
        status: value.status,
        title: value.title,
        endDate: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.endDate)),
        description: value.description,
        productionType: value.productionType,
        outcomes: value.outcomes,
        startDate: value.startDate
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    profile: [] | [_UserProfile];
    enrollments: Array<_Enrollment>;
}): {
    profile?: UserProfile;
    enrollments: Array<Enrollment>;
} {
    return {
        profile: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.profile)),
        enrollments: value.enrollments
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n25(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n23(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    bio: string;
    name: string;
    role: UserRole;
    email: string;
}): {
    id: Principal;
    bio: string;
    name: string;
    role: _UserRole;
    email: string;
} {
    return {
        id: value.id,
        bio: value.bio,
        name: value.name,
        role: to_candid_UserRole_n8(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
